name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}
        git config --global user.name ${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}
        git remote set-url origin https://${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}@github.com/vaimehro/demo-react-app>.git
        npm run deploy